### ISSUE TITLE
Kurang AnotationProcessor Butterknife compiler 8.5.1

### ISSUE THREAD

**Issue by ramdanix** [isfaaghyth/Kotlin-Starter#3]
jika terjadi error saat proses compile pada Android Studio 3.0

bisa ditambahkan anotationProcessor
annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'

semoga bermanfat :)

**Comment by isfaaghyth** [comment]
fixed! https://github.com/isfaaghyth/Kotlin-Starter/pull/5
